---
name: Check the Quality of the Code

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: read-all

jobs:
  # checking the quality of the code
  Super-Linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Install and run super-linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN}}
