---
name: Check Code Quality

on:
  push:
    branches: main
  pull_request:
    branches: main

permissions: read-all

jobs:
  Super-Linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout The Repository
        uses: actions/checkout@v4

      - name: Install and Run Super-Linter
        uses: github/super-linter@v6
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_GO: false
