---
name: Release to GitHub

on:
  push:
    branches: main
    paths: main.go

jobs:
  Build-and-Release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        # with:
        #   sparse-checkout: |
        # 'main.go'
        # 'gemini.conf.d/'

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "./go.mod"
          check-latest: true

      - name: Module Maintanance
        # run: go mod init "github.com/${{ github.repository }}"
        run: go mod tidy
      - run: go mod verify

      - name: Build
        run: go build -a -o gemini

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: "v1.0.${{ github.run_number }}"
          release_name: Gemini-AI CLI App
          draft: false
          prerelease: false
          body: Automated Release.

      - name: Archive gemini app and config directory
        run: zip -r Gemini-AI-CLI-App.zip gemini gemini.conf.d

      - name: Upload Release Binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "./Gemini-AI-CLI-App.zip"
          asset_name: Gemini-AI-CLI-App.zip
          asset_content_type: application/zip
